DroneBoxExpressApp/DroneBoxExpressApp/Commercial/urls.py
from django.urls import path
from DroneBoxExpressApp.Commercial import views

urlpatterns = [
    path('', views.OrdersView.as_view(), name='Orders-Page'),
    path('add/', views.CreateOrderView.as_view(), name='Create-Order-Page'),
    path('details/<int:pk>/', views.DetailsOrderView.as_view(), name='Details-Order-Page'),
    path('delete/<int:pk>/', views.DeleteOrderView.as_view(), name='Delete-Order-Page'),
    path('update/<int:pk>/', views.UpdateOrderView.as_view(), name='Update-Order-Page'),
    path('prices/', views.PricesListCreateView.as_view(), name='Prices-Page'),
    path('prices/<int:pk>/', views.PricesUpdateDeleteView.as_view(), name='Prices-Delete-Update-Page'),
    path('discounts/', views.DiscountsListCreateView.as_view(), name='Discount-Page'),
    path('discounts/<int:pk>/', views.DiscountsUpdateDeleteView.as_view(), name='Discount-Delete-Update-Page'),
]

DroneBoxExpressApp/DroneBoxExpressApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DroneBoxExpressApp.Common.urls')),
    path('accounts/', include('DroneBoxExpressApp.UserAccount.urls')),
    path('orders/', include('DroneBoxExpressApp.Commercial.urls')),
    path('operational/', include('DroneBoxExpressApp.Operational.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DroneBoxExpressApp/DroneBoxExpressApp/Commercial/models.py
from enum import Enum
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from DroneBoxExpressApp.Core.mixins import EnumMixin
from DroneBoxExpressApp.UserAccount.models import ProfileTypes, DroneBoxProfile
from DroneBoxExpressApp.Operational.models import RoutesModel, FlightModel


class OrderType(EnumMixin, Enum):
    Letter = "Letter"
    Parcel = "Parcel"
    Box = "Box"


class OrderStatus(EnumMixin, Enum):
    Pending = "Pending"
    Scheduled = "Scheduled"
    Completed = "Completed"
    Cancelled = "Cancelled"


class OrdersModel(models.Model):
    weight = models.FloatField(
        blank=False,
        null=False,
        validators=(
            MinValueValidator(0.0),
            MaxValueValidator(50.0),
        )
    )
    order_type = models.CharField(
        choices=OrderType.list_choices(),
        max_length=OrderType.max_len(),
        null=False,
        blank=False,
    )
    order_route = models.ForeignKey(
        to=RoutesModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    cost = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    order_status = models.CharField(
        choices=OrderStatus.list_choices(),
        max_length=OrderStatus.max_len(),
        default="Pending",
        null=False,
        blank=False,
    )
    order_profile = models.ForeignKey(
        to=DroneBoxProfile,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False
    )
    order_flight = models.ForeignKey(
        to=FlightModel,
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True
    )


# ----------- Models used with Django REST API via JS ------------
class PricesModel(models.Model):
    min_weight = models.PositiveIntegerField(blank=False, null=False)
    max_weight = models.PositiveIntegerField(blank=False, null=False)
    price_per_kg = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    target_order_type = models.CharField(
        choices=OrderType.list_choices(),
        max_length=OrderType.max_len(),
        null=False,
        blank=False,
    )


class DiscountsModel(models.Model):
    min_profile_revenue = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    max_profile_revenue = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    discount_rate = models.FloatField(
        blank=False,
        null=False,
        validators=(
            MinValueValidator(0.0),
            MaxValueValidator(1.0),
        ))
    discount_profile_type = models.CharField(
        choices=ProfileTypes.list_choices(),
        max_length=ProfileTypes.max_len(),
        null=False,
        blank=False,
    )

DroneBoxExpressApp/DroneBoxExpressApp/Commercial/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics as api_views
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from DroneBoxExpressApp.Commercial.models import PricesModel, OrdersModel, DiscountsModel
from DroneBoxExpressApp.Commercial.serializers import PricesSerializer, DiscountsSerializer
from DroneBoxExpressApp.Commercial.forms import OrderCreateForm
from DroneBoxExpressApp.UserAccount.models import DroneBoxProfile


class OrdersView(LoginRequiredMixin, views.ListView):
    template_name = "Commercial/orders_page.html"
    model = OrdersModel

    def get_queryset(self, *args, **kwargs):
        return OrdersModel.objects.filter(order_profile_id=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context


class CreateOrderView(LoginRequiredMixin, views.CreateView):
    model = OrdersModel
    form_class = OrderCreateForm
    template_name = "Commercial/order_create_page.html"
    success_url = reverse_lazy("Orders-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                revenue = profile.total_revenue
                profile_type = profile.profile_type
                context["profile"] = profile
                context["revenue"] = revenue
                context["profile_type"] = profile_type
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def form_valid(self, form):
        form_instance = form.instance
        try:
            temp_profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
        except Http404:
            return redirect("Access-Denied-Page")
        form_instance.order_profile = temp_profile
        form_instance.save()
        return super().form_valid(form)


class DetailsOrderView(LoginRequiredMixin, views.DetailView):
    model = OrdersModel
    template_name = "Commercial/order_details_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                order = get_object_or_404(OrdersModel, pk=self.kwargs["pk"])
            except Http404:
                return redirect("Access-Denied-Page")
            if profile != order.order_profile:
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class DeleteOrderView(LoginRequiredMixin, views.DeleteView):
    model = OrdersModel
    template_name = "Commercial/order_delete_page.html"
    success_url = reverse_lazy("Orders-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                order = get_object_or_404(OrdersModel, pk=self.kwargs["pk"])
            except Http404:
                return redirect("Access-Denied-Page")
            if profile != order.order_profile:
                return redirect("Access-Denied-Page")
            if order.order_status != "Pending":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class UpdateOrderView(LoginRequiredMixin, views.UpdateView):
    model = OrdersModel
    template_name = "Commercial/order_create_page.html"
    form_class = OrderCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                revenue = profile.total_revenue
                profile_type = profile.profile_type
                context["profile"] = profile
                context["revenue"] = revenue
                context["profile_type"] = profile_type
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def get_success_url(self):
        temp_pk = self.kwargs['pk']
        return reverse_lazy("Details-Order-Page", kwargs={'pk': temp_pk})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                order = get_object_or_404(OrdersModel, pk=self.kwargs["pk"])
            except Http404:
                return redirect("Access-Denied-Page")
            if profile != order.order_profile:
                return redirect("Access-Denied-Page")
            if order.order_status != "Pending":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


# Django REST Create and List View for PriceModel
class PricesListCreateView(api_views.ListCreateAPIView):
    queryset = PricesModel.objects.all()
    serializer_class = PricesSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]


# Django REST Details,Update,Delete view for PriceModel
class PricesUpdateDeleteView(api_views.RetrieveUpdateDestroyAPIView):
    serializer_class = PricesSerializer
    queryset = PricesModel.objects.all()
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated, IsAdminUser]
    lookup_url_kwarg = 'pk'


# Django REST Create and List View for DiscountsModel
class DiscountsListCreateView(api_views.ListCreateAPIView):
    queryset = DiscountsModel.objects.all()
    serializer_class = DiscountsSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]


# Django REST Details,Update,Delete view for DiscountsModel
class DiscountsUpdateDeleteView(api_views.RetrieveUpdateDestroyAPIView):
    serializer_class = DiscountsSerializer
    queryset = DiscountsModel.objects.all()
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated, IsAdminUser]
    lookup_url_kwarg = 'pk'

DroneBoxExpressApp/templates/Commercial/order_create_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            {% if form.weight.value %}
                <h1 class="section_heading" >Update Order</h1>
            {% else %}
                <h1 class="section_heading" >Create Order</h1>
            {% endif %}
            <form class="form_flex" method="post">
                {% csrf_token %}
                {{ profile_type|json_script:"profile_type" }}
                {{ revenue|json_script:"revenue" }}
                <p id="errors_p" style="display: none" hidden="true"></p>
                <p>{{ form.weight.errors }}</p>
                <p>{{ form.weight.label }} [kg]</p>
                <p>{{ form.weight }}</p>
                <p>{{ form.order_type.errors }}</p>
                <p>{{ form.order_type.label }}</p>
                <p>{{ form.order_type }}</p>
                <p>{{ form.order_route.errors }}</p>
                <p>{{ form.order_route.label }}</p>
                <p>
                    <select name="order_route" id="id_order_route" required="">
                        {% for entry in form.order_route %}
                            {% if entry|striptags != "(XXA) service_airport_1 to (XXB) service_airport_2" %}
                                {{ entry }}
                            {% endif %}
                        {% endfor %}
                    </select>
                </p>
                <div class="form_buttons_div">
                    <button class="a_button_inside" id="calc_btn">Calculate</button>
                </div>
                <p>{{ form.cost.errors }}</p>
                <div id="cost_div">
                    <p>{{ form.cost.label }}</p>
                    <p id="cost_field" >{{ form.cost }}</p>
                    <p>BGN</p>
                </div>
                <div class="form_buttons_div">
                    {% if form.weight.value %}
                        <button class="a_button_inside" id="order-submit-btn" type="submit">Save</button>
                        <a class="a_button_inside" href="{% url 'Details-Order-Page' object.pk %}">Back</a>
                    {% else %}
                        <button class="a_button_inside" id="order-submit-btn" type="submit">Create</button>
                        <a class="a_button_inside" href="{% url 'Orders-Page' %}">Back</a>
                    {% endif %}
                </div>
            </form>
        </section>
    </section>
    <script>
        window.URLS = {
            'prices': '{% url "Prices-Page" %}',
            'discounts': '{% url 'Discount-Page' %}',
            "route": '{% url "Details-Route-REST" 0 %}',
        }
    </script>
    <script src="{% static 'calculate_price.js' %}"></script>
{% endblock %}

DroneBoxExpressApp/templates/Commercial/order_delete_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading">Order Delete Page</h1>
            <form class="form_flex" method="post">
                {% csrf_token %}
                <h2 class="section_heading_h2">Are you sure tou want to delete</h2>
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Delete</button>
                    <a class="a_button_inside" href="{% url 'Details-Order-Page' object.pk %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Commercial/order_details_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading"> Order Details </h1>
            <div class="form_flex">
                <p>Order No.: {{ object.pk }}</p>
                <p>Weight: {{ object.weight }} kg</p>
                <p>Type: {{ object.order_type }}</p>
                <p>From &#187; {{ object.order_route.origin_airport }}</p>
                <p>To &#187; {{ object.order_route.destination_airport }}</p>
                <p>Distance: {{ object.order_route.distance }} km</p>
                <p>Price: {{ object.cost }} BGN</p>
                <p>Profile: {{ object.order_profile }}</p>
                <div class="form_buttons_div">
                    {% if object.order_status == "Pending" %}
                        <a class="a_button_inside" href="{% url 'Update-Order-Page' object.pk %}">Edit</a>
                        <a class="a_button_inside" href="{% url 'Delete-Order-Page' object.pk %}">Cancel</a>
                    {% endif %}
                        <a class="a_button_inside" href="{% url 'Orders-Page' %}">Back</a>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Commercial/orders_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <h1 class="section_heading">Orders Page</h1>
        <section class="orders_section">
            <div id="buttonsDiv" class="orders-navigation">
                {%  if request.user.is_authenticated %}
                    <button class="a_button" id="show-order-btn" onclick="showFunc()" hidden style="display: none;">Show Orders</button>
                    <a class="a_button" id="create-order-btn" href="{% url 'Create-Order-Page' %}">Create Order</a>
                    {% if request.user.is_staff %}
                        <button class="a_button" id="prices_btn">Prices</button>
                        <button class="a_button" id="discount_btn">Discounts</button>
                    {% endif %}
                    <a class="a_button" href="{% url 'Home-Page' %}">Back</a>
                {% endif %}
            </div>
            <div class="orders-info">
                <div class="orders-details" id="orders-window">
                    <section class="pending-orders">
                        <h2 class="section_heading_h2">Pending Orders</h2>
                        {% for obj in ordersmodel_list %}
                            {% if obj.order_status == "Pending" %}
                                <article class="ops_card">
                                    <p>Order No.: {{ obj.pk }}</p>
                                    <p>Weight: {{ obj.weight }} kg</p>
                                    <p>Type: {{ obj.order_type }}</p>
                                    <p>From &#187; {{ obj.order_route.origin_airport }}</p>
                                    <p>To &#187; {{ obj.order_route.destination_airport }}</p>
                                    <p>Price: {{ obj.cost }} BGN</p>
                                    <div class="ops_div_buttons">
                                        <a class="a_button_inside" href="{% url 'Details-Order-Page' obj.pk %}">Details</a>
                                    </div>
                                </article>
                            {% endif %}
                        {% endfor %}
                    </section>
                    <section class="scheduled-orders">
                        <h2 class="section_heading_h2">Scheduled Orders</h2>
                        {% for obj in ordersmodel_list %}
                            {% if obj.order_status == "Scheduled" %}
                                <article class="ops_card">
                                    <p>Order No.: {{ obj.pk }}</p>
                                    <p>Weight: {{ obj.weight }} kg</p>
                                    <p>Type: {{ obj.order_type }}</p>
                                    <p>From &#187; {{ obj.order_route.origin_airport }}</p>
                                    <p>To &#187; {{ obj.order_route.destination_airport }}</p>
                                    <p>Price: {{ obj.cost }} BGN</p>
                                    <div class="ops_div_buttons">
                                        <a class="a_button_inside" href="{% url 'Details-Order-Page' obj.pk %}">Details</a>
                                    </div>
                                </article>
                            {% endif %}
                        {% endfor %}
                    </section>
                    <section class="completed-orders">
                        <h2 class="section_heading_h2">Completed Orders</h2>
                        {% for obj in ordersmodel_list %}
                            {% if obj.order_status == "Completed" %}
                                <article class="ops_card">
                                    <p>Order No.: {{ obj.pk }}</p>
                                    <p>Weight: {{ obj.weight }} kg</p>
                                    <p>Type: {{ obj.order_type }}</p>
                                    <p>From &#187; {{ obj.order_route.origin_airport }}</p>
                                    <p>To &#187; {{ obj.order_route.destination_airport }}</p>
                                    <p>Price: {{ obj.cost }} BGN</p>
                                    <div class="ops_div_buttons">
                                        <a class="a_button_inside" href="{% url 'Details-Order-Page' obj.pk %}">Details</a>
                                    </div>
                                </article>
                            {% endif %}
                        {% endfor %}
                    </section>
                </div>
                <div>
                    <ul class="prices-details" id="prices-window" style="display: none;"></ul>
                </div>
                <div>
                    <ul class="discount-details" id="discount-window" style="display: none;"></ul>
                </div>
            </div>
        </section>
    </section>
    <script>
        window.URLS = {
            'prices': '{% url "Prices-Page" %}',
            'discounts': '{% url 'Discount-Page' %}'
        }
    </script>
    <script>
        function checkNumber(event) {
            let aCode = event.which ? event.which : event.keyCode;
            if (aCode > 31 && (aCode < 48 || aCode > 57)) return false;
            return true;
        }
    </script>
    <script src="{% static 'prices_front_end.js' %}"></script>
    <script src="{% static 'discounts_front_end.js' %}"></script>
    <script src="{% static 'show_order_functionality.js' %}"></script>
{% endblock %}