DroneBoxExpressApp/DroneBoxExpressApp/Operational/urls.py
from django.urls import path
from DroneBoxExpressApp.Operational import views

urlpatterns = [
    path('', views.OperationalView.as_view(), name='Operations-Page'),
    path('airports/add/', views.CreateAirportView.as_view(), name='Create-Airport-Page'),
    path('airports/edit/<int:pk>/', views.EditAirportView.as_view(), name='Edit-Airport-Page'),
    path('drones/add/', views.CreateDroneView.as_view(), name='Create-Drone-Page'),
    path('drones/edit/<int:pk>/', views.EditDroneView.as_view(), name='Edit-Drone-Page'),
    path('routes/add/', views.CreateRouteView.as_view(), name='Create-Route-Page'),
    path('routes/edit/<int:pk>', views.EditRouteView.as_view(), name='Edit-Route-Page'),
    path('routes/delete/<int:pk>', views.DeleteRouteView.as_view(), name='Delete-Route-Page'),
    path('routes/rest/<int:pk>/', views.DetailsRouteRESTView.as_view(), name='Details-Route-REST'),
    path('flights/edit/<int:pk>', views.EditFlightsView.as_view(), name='Edit-Flight-Page'),
    path('flights/delete/<int:pk>', views.DeleteFlightsView.as_view(), name='Delete-Flight-Page'),
]

DroneBoxExpressApp/DroneBoxExpressApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DroneBoxExpressApp.Common.urls')),
    path('accounts/', include('DroneBoxExpressApp.UserAccount.urls')),
    path('orders/', include('DroneBoxExpressApp.Commercial.urls')),
    path('operational/', include('DroneBoxExpressApp.Operational.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DroneBoxExpressApp/DroneBoxExpressApp/Operational/models.py
from enum import Enum
from django.core.validators import MinValueValidator, MinLengthValidator, MaxValueValidator
from django.db import models
from django.core.exceptions import ValidationError
from DroneBoxExpressApp.Core.additional_functions import distance_calculator, fuel_cost
from DroneBoxExpressApp.Core.mixins import EnumMixin
from DroneBoxExpressApp.UserAccount.models import DroneBoxProfile


class FlightStatus(EnumMixin, Enum):
    Scheduled = "Scheduled"
    Completed = "Completed"
    Cancelled = "Cancelled"


class DroneModel(models.Model):
    model_name = models.CharField(blank=False, null=False, max_length=30)
    mtow = models.PositiveIntegerField(blank=False, null=False, validators=[MaxValueValidator(9000000)])
    range = models.PositiveIntegerField(blank=False, null=False, validators=[MaxValueValidator(9000000)])
    fuel_burn_rate = models.FloatField(blank=False, null=False, validators=[
        MinValueValidator(0.0),
        MaxValueValidator(9000000)
    ])

    def __str__(self):
        return self.model_name


class AirportModel(models.Model):
    airport_name = models.CharField(blank=False, null=False, max_length=50)
    iata_code = models.CharField(
        blank=False,
        null=False,
        max_length=3,
        validators=[MinLengthValidator(3)]
    )
    longitude = models.FloatField(blank=False, null=False)
    latitude = models.FloatField(blank=False, null=False)
    operational_cost = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    fuel_cost = models.FloatField(blank=True, null=False, default=fuel_cost, validators=[MinValueValidator(0.0)])

    def __str__(self):
        return f'({self.iata_code}) {self.airport_name}'


class RoutesModel(models.Model):
    origin_airport = models.ForeignKey(
        to=AirportModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
        related_name='Route_Origin_Airport'
    )
    destination_airport = models.ForeignKey(
        to=AirportModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
        related_name='Route_Destination_Airport'
    )
    route_drone = models.ForeignKey(
        to=DroneModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False
    )
    maximum_capacity = models.FloatField(
        validators=[MinValueValidator(0.0)],
        editable=False,
        blank=False,
        null=False
    )
    current_capacity = models.FloatField(
        blank=True,
        null=False,
        default=0.0,
        validators=[MinValueValidator(0.0)]
    )
    distance = models.FloatField(editable=False, blank=False, null=False, validators=[MinValueValidator(0.0)])

    def clean(self):
        distance = distance_calculator(
            self.origin_airport.latitude,
            self.origin_airport.longitude,
            self.destination_airport.latitude,
            self.destination_airport.longitude
        )
        if distance < 1:
            raise ValidationError("Origin Airport is the same as Destination Airport")
        else:
            self.distance = distance

    def save(self, *args, **kwargs):
        self.maximum_capacity = self.route_drone.mtow
        super(RoutesModel, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.origin_airport} to {self.destination_airport}"


class FlightModel(models.Model):
    flight_origin_airport = models.ForeignKey(
        to=AirportModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
        related_name='Flight_Origin_Airport'
    )
    flight_destination_airport = models.ForeignKey(
        to=AirportModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
        related_name='Flight_Destination_Airport'
    )
    flight_drone = models.ForeignKey(
        to=DroneModel,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False
    )
    flight_distance = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    flight_capacity = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])
    flight_status = models.CharField(
        choices=FlightStatus.list_choices(),
        max_length=FlightStatus.max_len(),
        default="Scheduled",
        null=False,
        blank=False,
    )
    drone_operator = models.ForeignKey(
        to=DroneBoxProfile,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False
    )

    def __str__(self):
        return f"{self.flight_origin_airport} to {self.flight_destination_airport}"

DroneBoxExpressApp/DroneBoxExpressApp/Operational/forms.py
from django import forms
from DroneBoxExpressApp.Operational.models import AirportModel, DroneModel, RoutesModel, FlightModel


class AirportCreateForm(forms.ModelForm):
    class Meta:
        model = AirportModel
        fields = ["airport_name", "iata_code", "longitude", "latitude", "operational_cost", "fuel_cost"]


class AirportEditForm(forms.ModelForm):
    class Meta:
        model = AirportModel
        fields = ["airport_name", "iata_code", "operational_cost", "fuel_cost"]


class DroneCreateForm(forms.ModelForm):
    class Meta:
        model = DroneModel
        fields = ["model_name", "mtow", "range", "fuel_burn_rate"]


class DroneEditForm(forms.ModelForm):
    class Meta:
        model = DroneModel
        fields = ["model_name", "range", "fuel_burn_rate"]


class RouteCreateForm(forms.ModelForm):
    class Meta:
        model = RoutesModel
        fields = ["origin_airport", "destination_airport", "route_drone"]


class FlightCompleteForm(forms.ModelForm):
    class Meta:
        model = FlightModel
        fields = ["flight_status"]

DroneBoxExpressApp/DroneBoxExpressApp/Operational/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic as views
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics as api_views
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from DroneBoxExpressApp.Operational.serializers import RoutesSerializer
from DroneBoxExpressApp.Operational.models import RoutesModel, DroneModel, AirportModel, FlightModel
from DroneBoxExpressApp.Operational.forms import AirportCreateForm, DroneCreateForm, RouteCreateForm
from DroneBoxExpressApp.Operational.forms import AirportEditForm, DroneEditForm, FlightCompleteForm
from DroneBoxExpressApp.UserAccount.models import DroneBoxProfile


class OperationalView(LoginRequiredMixin, views.TemplateView):
    template_name = "Operational/operational_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
                if profile:
                    pilot_flights = FlightModel.objects.filter(drone_operator=profile)
                    routes = RoutesModel.objects.all()
                    airports = AirportModel.objects.all()
                    drones = DroneModel.objects.all()
                    context["pilot_flights"] = pilot_flights
                    context["routes"] = routes
                    context["airports"] = airports
                    context["drones"] = drones
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class CreateAirportView(LoginRequiredMixin, views.CreateView):
    model = AirportModel
    form_class = AirportCreateForm
    template_name = "Operational/airport_create_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class EditAirportView(LoginRequiredMixin, views.UpdateView):
    model = AirportModel
    form_class = AirportEditForm
    template_name = "Operational/airport_edit_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class CreateDroneView(LoginRequiredMixin, views.CreateView):
    model = DroneModel
    form_class = DroneCreateForm
    template_name = "Operational/drone_create_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class EditDroneView(LoginRequiredMixin, views.UpdateView):
    model = DroneModel
    form_class = DroneEditForm
    template_name = "Operational/drone_edit_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class CreateRouteView(LoginRequiredMixin, views.CreateView):
    model = RoutesModel
    form_class = RouteCreateForm
    template_name = "Operational/route_create_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class EditRouteView(LoginRequiredMixin, views.UpdateView):
    model = RoutesModel
    form_class = RouteCreateForm
    template_name = "Operational/route_create_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
                context["profile"] = profile
            except Http404:
                context["profile"] = "Not Logged In"
        else:
            context["profile"] = "Not Logged In"
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        else:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)
            except Http404:
                return redirect("Access-Denied-Page")
            if profile.profile_type != "Pilot":
                return redirect("Access-Denied-Page")
        return super().dispatch(request, *args, **kwargs)


class DeleteRouteView(LoginRequiredMixin, views.DeleteView):
    model = RoutesModel
    template_name = "Operational/route_delete_page.html"
    success_url = reverse_lazy("Operations-Page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                profile = get_object_or_404(DroneBoxProfile, pk=self.request.user.pk)

DroneBoxExpressApp/templates/Operational/airport_create_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading" >Add New Airport</h1>
            <form class="form_flex" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Add</button>
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/airport_edit_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading" >Edit Airport</h1>
            <form class="form_flex" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Save</button>
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/drone_create_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading">Add New Drone Model</h1>
            <form class="form_flex" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Add</button>
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/drone_edit_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading">Update Drone Specifications</h1>
            <form class="form_flex" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Update</button>
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/flight_canncellation_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h2 class="section_heading">Cancel Current Flight</h2>
            <form class="form_flex" method="post">
                {% csrf_token %}
                <h1 class="section_heading_h2">Are you sure you want to cancel</h1>
                <p>Flight No.: {{ object.pk }}</p>
                <p>Current Flight Capacity: {{ object.flight_capacity }} kg</p>
                <p>From &#187; {{ object.flight_origin_airport }}</p>
                <p>To &#187; {{ object.flight_destination_airport }}</p>
                <p>Drone Model: {{ object.flight_drone }}</p>
                <p>Flight Distance: {{ object.flight_distance }} km</p>
                <p>Flight Status: {{ object.flight_status }}</p>
                <p>Pilot: {{ object.drone_operator }}</p>
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Cancel</button>
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/flight_compelte_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            <h1 class="section_heading">Complete Current Flight</h1>
            <form class="form_flex" method="post">
                {% csrf_token %}
                <p>{{ form.flight_status.errors }}</p>
                <p>{{ form.flight_status.label }}</p>
                <p>
                    <select name="flight_status" id="id_flight_status" required="">
                        {% for entry in form.flight_status %}
                            {% if entry|striptags != "Cancelled" %}
                                {{ entry }}
                            {% endif %}
                        {% endfor %}
                    </select>
                </p>
                <div class="form_buttons_div">
                    <button class="a_button_inside" type="submit">Complete</button>
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/operational_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <h1 class="section_heading">Operations</h1>
        <section class="main_ops_section">
            <div class="flights_div ops_div">
                <h2 class="section_heading_h2" >Flights Menu</h2>
                {% if pilot_flights %}
                    {% for flight in pilot_flights %}
                        {% if flight.flight_status != "Completed" and  flight.flight_status != "Cancelled"%}
                            {% if flight != "(XXA) service_airport_1 to (XXB) service_airport_2" %}
                                <article class="ops_card" >
                                    <p>Flight No.: {{ flight.pk }}</p>
                                    <p>From &#187; {{ flight.flight_origin_airport }}</p>
                                    <p>To &#187; {{ flight.flight_destination_airport }}</p>
                                    <p>Flight Status: {{ flight.flight_status }}</p>
                                    <p>Pilot: {{ flight.drone_operator }}</p>
                                    <div class="ops_div_buttons">
                                        <a class="a_button_inside" href="{% url 'Edit-Flight-Page' flight.pk %}">Complete</a>
                                        <a class="a_button_inside" href="{% url 'Delete-Flight-Page' flight.pk %}">Cancel</a>
                                    </div>
                                </article>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div>
                        There are no Flights
                    </div>
                {% endif %}
            </div>
            <div class="routes_div ops_div">
                <h2 class="section_heading_h2" >Routes Menu</h2>
                <a class="a_button_inside" href="{% url 'Create-Route-Page' %}">Add Route</a>
                {% if routes %}
                    {% for route in routes %}
                        {% if route|striptags != "(XXA) service_airport_1 to (XXB) service_airport_2" %}
                            <article class="ops_card" >
                                <p>From &#187; {{ route.origin_airport }}</p>
                                <p>To &#187; {{ route.destination_airport }}</p>
                                <p>Capacity: {{ route.maximum_capacity }} kg</p>
                                <div class="ops_div_buttons">
                                    <a class="a_button_inside" href="{% url 'Edit-Route-Page' route.pk %}">Edit</a>
                                    <a class="a_button_inside" href="{% url 'Delete-Route-Page' route.pk %}">Delete</a>
                                </div>
                            </article>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div>
                        There are no Routes
                    </div>
                {% endif %}
            </div>
            <div class="airports_div ops_div">
                <h2 class="section_heading_h2" >Airports Menu</h2>
                <a class="a_button_inside" href="{% url 'Create-Airport-Page' %}">Add Airport</a>
                {% if airports %}
                    {% for airport in airports %}
                        {% if airport|striptags != "(XXA) service_airport_1" and airport|striptags != "(XXB) service_airport_2"%}
                            <article class="ops_card" >
                                <p>Name: {{ airport }}</p>
                                <p>Operational Cost: {{ airport.operational_cost }} BGN</p>
                                <p>LON: {{ airport.longitude }} &#8212; LAT: {{ airport.latitude }}</p>
                                <div class="ops_div_buttons">
                                    <a class="a_button_inside" href="{% url 'Edit-Airport-Page' airport.pk %}">Edit</a>
                                </div>
                            </article>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div>
                        There are no Airports
                    </div>
                {% endif %}
            </div>
            <div class="drones_div ops_div">
                <h2 class="section_heading_h2" >Drones Menu</h2>
                <a class="a_button_inside" href="{% url 'Create-Drone-Page' %}">Add Drone</a>
                {% if drones %}
                    {% for drone in drones %}
                        {% if drone|striptags != "service_drone" %}
                            <article class="ops_card" >
                                <p>Model: {{ drone }}</p>
                                <p>MTOW: {{ drone.mtow }} kg</p>
                                <p>Range: {{ drone.range }} km</p>
                                <div class="ops_div_buttons">
                                    <a class="a_button_inside" href="{% url 'Edit-Drone-Page' drone.pk %}">Edit</a>
                                </div>
                            </article>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div>
                        There are no Drones
                    </div>
                {% endif %}
            </div>
        </section>
    </section>
{% endblock %}

DroneBoxExpressApp/templates/Operational/route_create_page.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section class="main_section">
        <section class="form_section">
            {% if form.origin_airport.value %}
                <h1 class="section_heading">Update Current Route</h1>
            {% else %}
                <h1 class="section_heading">Create a New Route</h1>
            {% endif %}
            <form class="form_flex" method="post">
                {% csrf_token %}
                <p>{{ form.origin_airport.errors }}</p>
                <p>{{ form.origin_airport.label }}</p>
                <p>
                    <select name="origin_airport" id="id_origin_airport" required="">
                        {% for entry in form.origin_airport %}
                            {% if entry|striptags != "(XXA) service_airport_1" and entry|striptags != "(XXB) service_airport_2" %}
                                {{ entry }}
                            {% endif %}
                        {% endfor %}
                    </select>
                </p>
                <p>{{ form.destination_airport.errors }}</p>
                <p>{{ form.destination_airport.label }}</p>
                <p>
                    <select name="destination_airport" id="id_destination_airport" required="">
                        {% for entry in form.destination_airport %}
                            {% if entry|striptags != "(XXA) service_airport_1" and entry|striptags != "(XXB) service_airport_2" %}
                                {{ entry }}
                            {% endif %}
                        {% endfor %}
                    </select>
                </p>
                <p>{{ form.route_drone.errors }}</p>
                <p>{{ form.route_drone.label }}</p>
                <p>
                    <select name="route_drone" id="id_route_drone" required="">
                        {% for entry in form.route_drone %}
                            {% if entry|striptags != "service_drone" %}
                                {{ entry }}
                            {% endif %}
                        {% endfor %}
                    </select>
                </p>
                <div class="form_buttons_div">
                    {% if form.origin_airport.value %}
                        <button class="a_button_inside" type="submit">Save</button>
                    {% else %}
                        <button class="a_button_inside" type="submit">Create</button>
                    {% endif %}
                    <a class="a_button_inside" href="{% url 'Operations-Page' %}">Back</a>
                </div>
            </form>
        </section>
    </section>
{% endblock %}